app:
    resource: '@AppBundle/Controller/'
    type: annotation

app_show_command_form:
    path:      /showform
    defaults:
        _controller: AppBundle:Command:showCommandForm

app_show_tickets_forms:
    path:      /showticketsforms
    defaults:
        _controller: AppBundle:Command:showTicketsForms
