app:
    resource: '@AppBundle/Controller/'
    type: annotation

app_command:
    path:      /command
    defaults:
        _controller: AppBundle:Command:command

app_tickets:
    path:      /tickets
    defaults:
        _controller: AppBundle:Command:tickets

app_command_payment:
    path:      /command/payment
    defaults:
        _controller: AppBundle:Command:payment

app_home:
    path:       /home
    defaults:
        _controller: AppBundle:Home:home

app_contact:
    path:       /contact
    defaults:
        _controller: AppBundle:Contact:contact