app:
    resource: '@AppBundle/Controller/'
    type: annotation

app_command:
    path:      /command
    defaults:
        _controller: AppBundle:Command:command

app_tickets:
    path:      /tickets
    defaults:
        _controller: AppBundle:Command:tickets

app_command_payment:
    path:      /command/payment
    defaults:
        _controller: AppBundle:Command:payment
