app:
    resource: '@AppBundle/Controller/'
    type: annotation

app_command:
    path:      /command
    defaults:
        _controller: AppBundle:Command:command

app_tickets:
    path:      /tickets
    defaults:
        _controller: AppBundle:Command:tickets

app_bill:
    path:      /bill
    defaults:
        _controller: AppBundle:Command:bill

order_prepare:
    path:      /order/prepare
    defaults:
        _controller: AppBundle:Order:prepare
